---
title: "Spotify data exploration"
output: html_notebook
---

This notebook is made to explore my spotify data in order to make a shiny app out of it.

Set up:

```{r}
# to be able to see japanese characters
Sys.setlocale("LC_ALL", "English_United States.932")
```

Parameters:

```{r}
json_file_path <- "E:/Dropbox/datos-spotify/20181204/StreamingHistory.json"
```

Extract json data:

```{r}
# reading my streaming history into a data table
dt <- data.table::as.data.table(jsonlite::read_json(path = json_file_path, simplifyVector = TRUE))
```

```{r}
dt$fecha <- data.table::as.IDate(dt$endTime)
dt$tiempo <- data.table::as.ITime(dt$endTime)
dt$tiempoPOSIXct <- as.POSIXct(dt$tiempo)              
```


```{r circular barplot}
library(tidyverse)
# ----- This section prepare a dataframe for labels ---- #
label_data = data.table::as.data.table(table(dt$artistName[]))
colnames(label_data) <- c("artista", "value")
label_data <- label_data[ which(label_data$value > 50), ]
label_data$value <- 100 * label_data$value / max(label_data$value)
label_data$id <- seq.int(nrow(label_data))
label_data$label_av <- paste(label_data$artista, round(label_data$value, digits = 0))

# calculate the ANGLE of the labels
number_of_bar=nrow(label_data)
angle= 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
 
# calculate the alignment of labels: right or left
# If I am on the left part of the plot, my labels have currently an angle < -90
label_data$hjust<-ifelse( angle < -90, 1, 0)
 
# flip angle BY to make them readable
label_data$angle<-ifelse(angle < -90, angle+180, angle)
# ----- ------------------------------------------- ---- #
 
 
# Start the plot
p = ggplot(label_data, aes(x=as.factor(id), y=value)) +       # Note that id is a factor. If x is numeric, there is some space between the first bar
  
  # This add the bars with a blue color
  geom_bar(stat="identity", fill=alpha("skyblue", 0.7)) +
  
  # Limits of the plot = very important. The negative value controls the size of the inner circle, the positive one is useful to add size over each bar
  ylim(-100,250) +
  
  # Custom the theme: no axis title and no cartesian grid
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(0.5,4), "cm")      # Adjust the margin to make in sort labels are not truncated!
  ) +
  
  # This makes the coordinate polar instead of cartesian.
  coord_polar(start = 0) +
  
  # Add the labels, using the label_data dataframe that we have created before
  geom_text(data=label_data, aes(x=id, y=value+10, label=label_av, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2, angle= label_data$angle, inherit.aes = FALSE )
 
p
 
```

```{r scatter}

p <- qplot(fecha, as.POSIXct(tiempo, tz=""), data=dt, xlab="fecha", ylab="tiempo")

p
```

```{r plotly scatter}
p2 <- plotly::plot_ly(data = dt, x = ~fecha, y = ~tiempoPOSIXct)
p2
```


G. Nicolás Villalobos Zaid


